export const articleFaqSchemaBySlug: Record<string, Array<{ question: string; answer: string }>> = {
  "bambino-che-non-ascolta-cosa-fare-senza-urlare": [
    { question: "Perché mio figlio mi ascolta solo quando urlo?", answer: "Perché probabilmente ha imparato che l'urlo è il vero segnale di azione. Serve ricostruire richieste chiare e conseguenze coerenti prima di arrivare alla rabbia." },
    { question: "Un bambino che non ascolta è maleducato?", answer: "Non sempre. Può essere stanco, immerso nel gioco, poco abituato alle routine o in difficoltà con i limiti. Va osservata la dinamica, non solo il comportamento." },
    { question: "Come posso farmi ascoltare senza punizioni?", answer: "Usa poche regole chiare, richieste brevi, anticipazioni e conseguenze naturali. La fermezza non coincide con la punizione." },
    { question: "A che età un bambino dovrebbe ascoltare?", answer: "L'ascolto cresce gradualmente. Anche a 6 o 7 anni un bambino ha bisogno di guida, routine e adulti coerenti per autoregolarsi." },
    { question: "Quando il non ascolto diventa un problema?", answer: "Quando è costante, crea conflitti quotidiani, compromette scuola o routine familiari e lascia gli adulti senza strumenti." },
    { question: "La pedagogista può aiutare con le regole in casa?", answer: "Sì. La consulenza pedagogica aiuta i genitori a costruire regole sostenibili, routine chiare e modalità comunicative più efficaci." },
  ],
  "capricci-nei-bambini-cause-come-gestirli": [
    { question: "I capricci sono normali?", answer: "Sì, soprattutto nei primi anni. Diventano da osservare quando sono molto intensi, frequenti o ingestibili nella vita quotidiana." },
    { question: "Devo ignorare i capricci?", answer: "Non sempre. Puoi ignorare alcune provocazioni lievi, ma una crisi emotiva va contenuta con presenza, poche parole e limiti chiari." },
    { question: "Se cedo una volta rovino tutto?", answer: "No. Conta la direzione generale. Però se cedere diventa la regola, il bambino impara che la crisi è efficace." },
    { question: "Come fermare un capriccio in pubblico?", answer: "Riduci gli stimoli, parla poco, mantieni il limite e spostati se serve. L'obiettivo non è salvare l'apparenza, ma guidare il bambino." },
    { question: "Capricci e crisi emotive sono la stessa cosa?", answer: "Non sempre. Alcune crisi sono scariche emotive intense, non richieste volontarie. Osservare causa, durata e contesto aiuta a capirlo." },
    { question: "Quando serve una consulenza?", answer: "Quando le crisi sono quotidiane, la famiglia è esausta o non si riesce più a mantenere regole senza urlare o cedere sempre." },
  ],
  "uso-cellulare-bambini-limiti-rischi-regole": [
    { question: "A che età dare il cellulare a un bambino?", answer: "Non esiste un'età uguale per tutti, ma prima di un uso personale servono maturità, regole e supervisione. Nei bambini piccoli è preferibile un uso limitato e condiviso." },
    { question: "Quanto tempo di schermo è troppo?", answer: "Dipende da età, contenuti e contesto. Diventa troppo quando sostituisce sonno, gioco, movimento, relazione e autonomia." },
    { question: "Come togliere il cellulare senza crisi?", answer: "Anticipa, usa un timer, mantieni la regola e offri un passaggio alternativo. Le prime proteste non significano che la regola sia sbagliata." },
    { question: "Il cellulare fa male ai bambini?", answer: "Non è l'oggetto in sé, ma l'uso eccessivo, non supervisionato o usato come calmante continuo a creare rischi educativi." },
    { question: "Meglio vietare del tutto?", answer: "Di solito è più utile educare all'uso che vietare senza progetto. Alcuni momenti, però, dovrebbero restare senza schermi." },
    { question: "La pedagogista può aiutare sulle regole digitali?", answer: "Sì. Può aiutare la famiglia a costruire limiti realistici, routine e alternative adatte all'età del bambino." },
  ],
  "ansia-nei-bambini-segnali-come-aiutarli": [
    { question: "Come capire se mio figlio ha ansia?", answer: "Osserva se paure, sintomi fisici, evitamenti o bisogno di rassicurazione sono frequenti e limitano la sua vita quotidiana." },
    { question: "L'ansia nei bambini passa da sola?", answer: "A volte alcune paure evolutive passano, ma se l'ansia persiste o aumenta è meglio chiedere un confronto professionale." },
    { question: "Cosa dire a un bambino ansioso?", answer: "Puoi dire: “Vedo che sei preoccupato. Sono qui. Facciamo un passo alla volta”. Accogliere e guidare è più utile che minimizzare." },
    { question: "Devo evitare ciò che gli fa paura?", answer: "Non sempre. L'evitamento continuo può rinforzare l'ansia. Meglio costruire esposizioni graduali e accompagnate." },
    { question: "Ansia e capricci possono somigliarsi?", answer: "Sì. Alcuni comportamenti oppositivi nascondono paura o insicurezza. Per questo è importante leggere il contesto." },
    { question: "Quando serve uno psicologo?", answer: "Se l'ansia è molto intensa, causa grande sofferenza o sintomi importanti, può essere utile una valutazione psicologica insieme al supporto educativo." },
  ],
  "difficolta-a-scuola-quando-preoccuparsi": [
    { question: "Quando preoccuparsi per le difficoltà a scuola?", answer: "Quando durano nel tempo, causano forte stress o incidono su autostima, motivazione e vita familiare." },
    { question: "Voti bassi significano DSA?", answer: "Non necessariamente. I voti bassi possono dipendere da metodo, emozioni, attenzione, motivazione o difficoltà specifiche da approfondire." },
    { question: "Come aiutare nei compiti senza sostituirsi?", answer: "Guida il metodo con domande, routine e piccoli obiettivi, lasciando al bambino la responsabilità del compito." },
    { question: "Mio figlio è pigro o in difficoltà?", answer: "Prima di parlare di pigrizia osserva dove si blocca. Spesso l'evitamento nasce da frustrazione o mancanza di strategie." },
    { question: "Quando serve tutoraggio specialistico?", answer: "Quando mancano metodo, autonomia, organizzazione o quando BES, DSA o ADHD richiedono strategie personalizzate." },
    { question: "La pedagogista parla anche con la scuola?", answer: "Quando utile e con accordo della famiglia, può favorire un dialogo educativo tra genitori, insegnanti e ragazzo." },
  ],
  "come-migliorare-autostima-bambini-strategie": [
    { question: "Come capire se un bambino ha bassa autostima?", answer: "Può evitare sfide, svalutarsi, cercare continua approvazione o reagire molto male agli errori." },
    { question: "Dire sempre bravo aiuta?", answer: "Aiuta di più un feedback specifico sul processo: impegno, strategia, coraggio, perseveranza." },
    { question: "Come aiutare un bambino che dice non sono capace?", answer: "Accogli la fatica e proponi un primo passo piccolo: “Proviamo insieme l'inizio, poi continui tu”." },
    { question: "L'autostima dipende dai genitori?", answer: "I genitori hanno un ruolo importante, ma contano anche scuola, esperienze, temperamento e relazioni." },
    { question: "Gli errori fanno male all'autostima?", answer: "No, se sono accompagnati bene. L'errore diventa dannoso quando viene umiliato o vissuto come misura del valore." },
    { question: "Quando chiedere aiuto?", answer: "Quando la svalutazione è frequente, limita le esperienze del bambino o crea sofferenza in famiglia e a scuola." },
  ],
  "bambini-aggressivi-perche-succede-come-intervenire": [
    { question: "Perché mio figlio picchia?", answer: "Può picchiare perché non riesce a gestire frustrazione, rabbia, gelosia o stanchezza. Il gesto va fermato e compreso." },
    { question: "Devo punire un bambino aggressivo?", answer: "Serve una conseguenza educativa, non umiliante: fermare, nominare, riparare e insegnare alternative." },
    { question: "Mordere è normale?", answer: "Nei piccoli può comparire, ma va sempre contenuto e accompagnato con parole e strategie alternative." },
    { question: "Cosa dire dopo che ha picchiato?", answer: "“Non ti lascio fare male. Eri arrabbiato. La prossima volta puoi chiamarmi o usare le parole”." },
    { question: "Quando preoccuparsi?", answer: "Quando l'aggressività è frequente, intensa, aumenta nel tempo o crea problemi a scuola e nelle relazioni." },
    { question: "La pedagogista può aiutare?", answer: "Sì. Può aiutare genitori e scuola a leggere cause, costruire confini e insegnare competenze emotive." },
  ],
  "inserimento-scolastico-difficile-come-aiutare": [
    { question: "Quanto dura un inserimento difficile?", answer: "Dipende dal bambino e dal contesto. Alcuni si adattano in pochi giorni, altri hanno bisogno di settimane e gradualità." },
    { question: "È meglio andare via mentre non guarda?", answer: "No. Salutare sempre protegge la fiducia, anche se il bambino piange." },
    { question: "Cosa dire quando piange all'ingresso?", answer: "“Lo so, è difficile. Io torno dopo. Ora resti con la maestra”. Poche parole, chiare e rassicuranti." },
    { question: "Il pianto significa che la scuola non va bene?", answer: "Non necessariamente. Va osservato insieme ad altri segnali e al racconto delle insegnanti durante la giornata." },
    { question: "Posso usare un premio?", answer: "Meglio non farne la strategia principale. Il bambino deve costruire fiducia, non entrare solo per ottenere qualcosa." },
    { question: "Quando chiedere supporto?", answer: "Quando il rifiuto è intenso, persistente o crea molta sofferenza nel bambino e nei genitori." },
  ],
  "litigi-tra-fratelli-come-gestirli": [
    { question: "È normale che i fratelli litighino sempre?", answer: "Un certo livello di conflitto è normale. Va osservato se è continuo, aggressivo o crea sofferenza stabile." },
    { question: "Devo intervenire in ogni litigio?", answer: "No, se non c'è rischio. Puoi osservare e intervenire come guida quando non riescono a trovare strategie." },
    { question: "Come gestire la gelosia?", answer: "Riconosci il bisogno di unicità, evita paragoni e crea piccoli tempi esclusivi con ciascun figlio." },
    { question: "È giusto dire al grande di cedere?", answer: "Non sempre. Il grande non deve essere responsabilizzato oltre la sua età. Anche il piccolo deve imparare limiti e attesa." },
    { question: "Le scuse vanno obbligate?", answer: "Meglio guidare una riparazione autentica. Le scuse forzate spesso insegnano forma, non responsabilità." },
    { question: "Quando chiedere una consulenza?", answer: "Quando i conflitti sono ingestibili, aggressivi o stanno logorando il clima familiare." },
  ],
  "genitori-oggi-errori-educativi-comuni": [
    { question: "Qual è l'errore educativo più comune?", answer: "Confondere il bisogno di amore con l'assenza di limiti. I bambini hanno bisogno di affetto e confini chiari." },
    { question: "Urlare ogni tanto rovina la relazione?", answer: "No, se l'adulto sa riparare. Il problema nasce quando l'urlo diventa la modalità principale." },
    { question: "Come essere genitori autorevoli?", answer: "Unisci calore e fermezza: ascolta le emozioni, ma mantieni regole sensate e coerenti." },
    { question: "Mamma e papà devono fare tutto uguale?", answer: "Non tutto, ma devono condividere le regole fondamentali per non creare confusione educativa." },
    { question: "Quando chiedere aiuto come genitori?", answer: "Quando vi sentite bloccati, in conflitto, sopraffatti o senza strumenti davanti ai comportamenti dei figli." },
    { question: "La consulenza pedagogica giudica i genitori?", answer: "No. Il suo scopo è aiutare la famiglia a capire cosa accade e costruire strategie concrete." },
  ],
};
